src/Sigma/AdminBundle/Entity/Notification.php
<?php

namespace Sigma\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Notification
 *
 * @ORM\Table(name="notification")
 * @ORM\Entity
 */
class Notification
{
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_create", type="datetime", nullable=true)
     */
    private $date_create;
    /**
     * @var string
     *
     * @ORM\Column(name="sujet", type="string", length=255, nullable=true)
     */
    private $sujet;
    /**
     * @var string
     *
     * @ORM\Column(name="contenu", type="string", length=255, nullable=true)
     */
    private $contenu;

    /**
     * @var integer
     *
     * @ORM\Column(name="point", type="integer", nullable=true)
     */
    private $point;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * Notification constructor.
     * @param \DateTime $date_create
     */
    public function __construct()
    {
        $datenow = new \DateTime("now", new \DateTimeZone("America/New_York"));
        $datenow->add(new \DateInterval("PT5H"));
        $this->date_create =$datenow ;
    }

    /**
     * @return string
     */
    public function getContenu()
    {
        return $this->contenu;
    }

    /**
     * @param string $contenu
     */
    public function setContenu($contenu)
    {
        $this->contenu = $contenu;
    }

    /**
     * @return int
     */
    public function getPoint()
    {
        return $this->point;
    }

    /**
     * @param int $point
     */
    public function setPoint($point)
    {
        $this->point = $point;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getSujet()
    {
        return $this->sujet;
    }

    /**
     * @param string $sujet
     */
    public function setSujet($sujet)
    {
        $this->sujet = $sujet;
    }

    /**
     * @return \DateTime
     */
    public function getDateCreate()
    {
        return $this->date_create;
    }

    /**
     * @param \DateTime $date_create
     */
    public function setDateCreate($date_create)
    {
        $this->date_create = $date_create;
    }


}

src/Sigma/AdminBundle/Controller/NotificationController.php
<?php

namespace Sigma\AdminBundle\Controller;

use Sigma\AdminBundle\Entity\Notification;
use Sigma\AdminBundle\Types\NotificationType;
use Sigma\AdminBundle\Types\UpdateNotificationType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use sngrl\PhpFirebaseCloudMessaging\Client;
use sngrl\PhpFirebaseCloudMessaging\Message;
use sngrl\PhpFirebaseCloudMessaging\Recipient\Device;

class NotificationController extends Controller
{
    public function listAction()
    {
        $em = $this->getDoctrine()->getManager();

        $Notifications = $em->getRepository('SigmaAdminBundle:Notification')->findAll();
        return $this->render('SigmaAdminBundle:Notification:List.htlm.twig', array('Notifications' => $Notifications));
    }

    public function addAction(Request $request)
    {

        $em = $this->getDoctrine()->getManager();

        $Notification = new Notification();
        $form = $this->createForm(NotificationType::class, $Notification);


        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($Notification);
            $em->flush();
            $server_key = 'AAAAQv0kcqE:APA91bGvdOSUEf2Kh9mELXM9U6Q1UgALrGGnpYixqJodlGS5c7KDJxgscEW0Rp79K8KNft2K2up8LjvFZtFcAdoplkEvjI6KibeDFAmkw_LA6KOqYlrxrytN8bk7Gz6DQvJWBreWs4Mo';
            $client = new Client();
            $client->setApiKey($server_key);
            $client->injectGuzzleHttpClient(new \GuzzleHttp\Client());


            $MobinauteHasDevices = $em->getRepository('SigmaAdminBundle:MobinauteHasDevices')->findAll();
            foreach ($MobinauteHasDevices as $mhd) {
                $message = new Message();
                $message->setPriority('high');
                $message->addRecipient(new Device($mhd->getDevices()->getRegid()));
                $message
                    ->setNotification(new \sngrl\PhpFirebaseCloudMessaging\Notification('Sigmat Audimat', $Notification->getContenu()))
                    ->setData(['title' => "Sigmat Audimat"
                        , 'message' => $Notification->getContenu()
                        , "id" => $Notification->getId(),
                        'sujet'=>$Notification->getSujet()]);
                $client->send($message);
            }
            return $this->redirectToRoute("sigma_admin_Notifications");
        }
        return $this->render('SigmaAdminBundle:Notification:Add.html.twig', array(
            'form' => $form->createView()
        ));
    }

    public function updateAction(Request $request, $id)
    {

        $em = $this->getDoctrine()->getManager();
        $Notification = $em->getRepository('SigmaAdminBundle:Notification')->find($id);

        $form = $this->createForm(UpdateNotificationType::class, $Notification);

        $form->handleRequest($request);
        if ($form->isValid()) {
            $em->persist($Notification);
            $em->flush();

            return ($this->redirectToRoute("sigma_admin_Notifications"));
        }

        return $this->render('@SigmaAdmin/Notification/Update.html.twig', array(
            'form' => $form->createView()
        ));
    }

    public function deleteAction($id)
    {

        $em = $this->getDoctrine()->getManager();
        $Question = $em->getRepository('SigmaAdminBundle:Notification')->find($id);
        $em->remove($Question);
        $em->flush();
        return $this->redirectToRoute("sigma_admin_Notifications");
    }
}

src/Sigma/AdminBundle/Resources/views/Notification/Add.html.twig
{% extends "SigmaAdminBundle::Layout.html.twig" %}
{% block PLUGIN %}

{% endblock %}
{% block content %}
    <div class="col s12 m12 l6">
        <div class="card-panel">
            <h4 class="header2">Add Notification</h4>
            <div class="row">
                {{ form_start(form) }}
                {{ form_errors(form) }}
                <form class="col s12">
                    <div class="row">
                        <div class="input-field col s12">
                            <div class="select-wrapper initialized">
                                {{ form_widget(form.sujet) }}
                                {{ form_errors(form.sujet) }}
                            </div>
                            <label for="first_name">Sujet</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="mdi-action-label prefix"></i>
                            {{ form_widget(form.contenu) }}
                            {{ form_errors(form.contenu) }}
                            <label for="first_name">Contenu</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="mdi-action-label prefix"></i>
                            {{ form_widget(form.point) }}
                            {{ form_errors(form.point) }}
                            <label for="first_name">Point</label>
                        </div>
                    </div>

                    <div class="row">
                        <div class="input-field col s12">
                            {{ form_widget(form.save) }}
                        </div>
                    </div>
                </form>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

src/Sigma/AdminBundle/Resources/views/Notification/List.htlm.twig
{% extends "SigmaAdminBundle::Layout.html.twig" %}
{% block PLUGIN %}
    <link href="{{ asset('Admin/js/plugins/prism/prism.css') }}" type="text/css" rel="stylesheet"
          media="screen,projection">
    <link href="{{ asset('Admin/js/plugins/perfect-scrollbar/perfect-scrollbar.css') }}" type="text/css"
          rel="stylesheet" media="screen,projection">
    <link href="{{ asset('Admin/js/plugins/data-tables/css/jquery.dataTables.min.css') }}" type="text/css"
          rel="stylesheet" media="screen,projection">

{% endblock %}
{% block content %}
    <div id="table-datatables">
        <h4 class="header">List Des Questions</h4>
        <div class="row">
            <div class="col s12 m10 l12">
                <table id="data-table-simple" class="responsive-table display" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Sujet</th>
                        <th>Date</th>
                        <th>Question</th>
                        <th>Point</th>
                        <th>Option</th>
                    </tr>
                    </thead>

                    <tfoot>
                    <tr>
                        <th>Sujet</th>
                        <th>Date</th>
                        <th>Question</th>
                        <th>Point</th>
                        <th>Option</th>
                    </tr>
                    </tfoot>

                    <tbody>
                    {% for Notification in Notifications %}
                        <tr>
                            <td>{{ Notification.sujet }}</td>
                            <td>{{ Notification.dateCreate | date("m/d/Y H:i") }}</td>
                            <td>{{ Notification.contenu }}</td>
                            <td>{{ Notification.point }}</td>
                            <td>
                                <a href="{{ path('sigma_admin_update_Notification', { 'id': Notification.id }) }}" class="waves-effect waves-light btn-flat "><i class="mdi-editor-border-color right"></i></a>
                                <a href="{{ path('sigma_admin_delete_Notification', { 'id': Notification.id }) }}" class="waves-effect waves-light btn-flat "><i class="mdi-action-delete center"></i></a>
                                <a href="{{ path('sigma_admin_statistique_notification', { 'id': Notification.id }) }}" class="waves-effect waves-light btn-flat "><i class="fa fa-bar-chart left"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- Floating Action Button -->
    <div class="fixed-action-btn" style="bottom: 50px; right: 19px;">
        <a href="{{ path('sigma_admin_Add_Notification') }}" class="btn-floating blue btn-large">
            <i class="mdi-content-add"></i>
        </a>
    </div>
    <!-- Floating Action Button -->
{% endblock %}

src/Sigma/AdminBundle/Resources/views/Notification/Update.html.twig
{% extends "SigmaAdminBundle::Layout.html.twig" %}
{% block PLUGIN %}

{% endblock %}
{% block content %}
    <div class="col s12 m12 l6">
        <div class="card-panel">
            <h4 class="header2">Update Notification</h4>
            <div class="row">
                {{ form_start(form) }}
                {{ form_errors(form) }}
                <form class="col s12">
                    <div class="row">
                        <div class="input-field col s12">
                            <div class="select-wrapper initialized">
                                {{ form_widget(form.sujet) }}
                                {{ form_errors(form.sujet) }}
                            </div>
                            <label for="first_name">Sujet</label>
                        </div>
                    </div>                    <div class="row">
                        <div class="input-field col s12">
                            <i class="mdi-action-label prefix"></i>
                            {{ form_widget(form.contenu) }}
                            {{ form_errors(form.contenu) }}
                            <label for="first_name">Contenu</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="mdi-action-label prefix"></i>
                            {{ form_widget(form.point) }}
                            {{ form_errors(form.point) }}
                            <label for="first_name">Point</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            {{ form_widget(form.update) }}
                        </div>
                    </div>
                </form>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}